### ISSUE TITLE
Jiné texty po registraci/prodloužení pro AV ČR

### ISSUE THREAD

**Issue by jandera** [LIBCAS/BankID-Registrator#11]
@TOA-Anakin Je potřeba rozdělit texty na běžné uživatele a zaměstnance AV ČR.

Jednak ty co se zobrazí po odeslání formuláře, kde se nastavuje heslo. Zaměstnanci AV ČR tam vůbec nebudou mít tu pasáž o poplatku a stejně tak po prodloužení.

Stejně tak ty texty co pak půjdou případně e-mailem, zaměstnanci tam opět nebudou mít zmínku o poplatku a jeho úhradě.

Texty pak dodáme, ale je potřeba to připravit

**Comment by TOA-Anakin** [comment]
@jandera Toto by melo byt hotovo uz pred 3 tydny

**Comment by jandera** [comment]
@TOA-Anakin Bezva, zavírám.
