### ISSUE TITLE
Prodlužování

### ISSUE THREAD

**Issue by jandera** [LIBCAS/BankID-Registrator#13]
@TOA-Anakin 
**1. zaškrtnuté checkboxy**
Při prodlužování u zaměstnance jsou po ověření v našem formuláři zaškrtnuté oba checkboxy:
"Jsem zaměstnanec AV ČR"
"Souhlasím se zpracováním osobních údajů *"

U běžného uživatele je zaškrtnutý:
"Souhlasím se zpracováním osobních údajů *"

Měly by být prázdné, aby uživatel musel udělat akci

**2. u zaměstnance už není kontrola na e-mail nebo drag&drop**

**3. Při prodlužování vznikne adresa 02 i když ji z našeho formuláře smažu, je prázdná jen se jménem (i to jméno jsem smazal)**
![image](https://github.com/user-attachments/assets/442ecf2f-353a-4f25-9fda-5149ecc92880)

**Comment by TOA-Anakin** [comment]
@jandera Tyto issues ohledně kontakní adresy by už měly být vyřesené

**Comment by jandera** [comment]
@TOA-Anakin Všechno vypadá vyřešené, jen u zaměstnance při prodlužování zůstává zaškrtnutý checkbox "Jsem zaměstnanec AV ČR", vzhledem k tomu, že mají platnost 3 roky, tak je pravděpodobné, že mezitím AV ČR opustili a že je checkbox zaškrtnutý si nemusí všimnout a my to pak třeba budeme považovat za pokus o podvod.

**Comment by TOA-Anakin** [comment]
@jandera opraven ten checkbox, na test serveru jsem samozrejme nastavil pro testovaci ucely, ze lze prodlouzit clenstvi i tem lidem, kterym se clenstvi jeste nechyli ke konci.

**Comment by jandera** [comment]
@TOA-Anakin Díky, zavírám.
