### ISSUE TITLE
Heslo

### ISSUE THREAD

**Issue by jandera** [LIBCAS/BankID-Registrator#15]
@TOA-Anakin Při nastavování hesla neprobíhá kontrola na délku hesla a také nelze použít speciální znaky, např. při použití % (zadal jsem "aaa%") registrace skončí chybou 500, patron se v Alephu založí, ale heslo má vygenerované systémem. Chtělo by to implementovat stejně, jako máme na https://lib.cas.cz/zapomenute-heslo

![image](https://github.com/user-attachments/assets/b263fcee-6dcf-4462-a199-c5be170c7601)

**Comment by TOA-Anakin** [comment]
@jandera se specialnimi znaky by uz nemel byt problem viz test server.

Validace bude v ramci jine vetsi upravy - dam vedet.

**Comment by TOA-Anakin** [comment]
@jandera validace pridana 

Heslo musi:
- mit 6 az 13 znaku
- obsahovat pismeno
- obsahovat cislici

Heslo muze:
- obsahovat specialni znaky

**Comment by jandera** [comment]
Bezva, zavírám.
