### ISSUE TITLE
Duplicitní ID03 - RFID při prodloužení

### ISSUE THREAD

**Issue by jandera** [LIBCAS/BankID-Registrator#16]
@TOA-Anakin Při prodloužení registrace a zadání jiného RFID = ID03 v Alephu zůstane i to původní

![image](https://github.com/user-attachments/assets/68ca88dc-0eac-4b1c-a4f2-277c12a80105)

asi by bylo dobré tam natáhnout hodnotu ID03 z Alephu, nechat pole editovatelné.

**Comment by jandera** [comment]
@TOA-Anakin Tohle ještě nezavírám, vypadá to že není vyřešeno, původní RFID/ID03 se sice natáhne, ale když zadám jiné, problém zůstává, vznikne další:
![image](https://github.com/user-attachments/assets/b022ff7d-13d4-444d-8f4d-f373ea59a077)

**Comment by TOA-Anakin** [comment]
@jandera 

opraveno, nahrano na test server
