### ISSUE TITLE
Bugy kontrol formuláře

### ISSUE THREAD

**Issue by jandera** [LIBCAS/BankID-Registrator#17]
@TOA-Anakin Pár kontrol ve formuláři se pokazilo:

1. když zaškrtnu, že jsem zaměstnanec a zadám e-mailovou adresu a nepřiložím soubor, tak to hlásí 
![image](https://github.com/user-attachments/assets/caab9261-41fc-48b2-b3ab-d26ed071e726)
přitom, by to zádný soubor/obrázek chtít nemělo - zadal jsem e-mail

2. Když nezadám telefonní šíslo, tak to hlásí:
![image](https://github.com/user-attachments/assets/c8cf8a27-2ffc-49e4-8521-c95f970f851c)
ale tohle pole má být nepovinné

**Comment by TOA-Anakin** [comment]
@jandera opraveno a otestovano
