### ISSUE TITLE
Změna vytvoření poplatku za registraci

### ISSUE THREAD

**Issue by jandera** [LIBCAS/BankID-Registrator#18]
@TOA-Anakin Protože stávající tvorba poplatku v sobě nese popis, který je v našem katalogu blokován na platbu kartou, prosím o změnu vytvoření poplatku, pouze tady u BankID registratoru.

Prosím, použít záznam 002922295, resp. jednotku 261100292229500001 až to bude nasazené, prosím o info abych otestoval a dal vědět Markovi, že je ok.

Díky

**Comment by TOA-Anakin** [comment]
@jandera upraveno a je to na test serveru
