### ISSUE TITLE
Vytvoří se prázdná kontaktní adresa (adresa 02 v Aleph)

### ISSUE THREAD

**Issue by jandera** [LIBCAS/BankID-Registrator#7]
@TOA-Anakin I pokud není vyplněné žádné pole v kontaktní adrese, tak se adresa 02 vy Alephu vytvoří, ta je pak ale systémově výchozí např. pro odesílání e-mailů atd. takže pokud tam nic není e-mail se neodešle.
![image](https://github.com/LIBCAS/BankID-Registrator/assets/18327175/c367b9b0-093a-42f0-a893-dc0caf547489)

Tzn. pokud jsou všechna pole v kontaktní adrese prázdná => nevytvořit adresu 02 v Alephu

A pak při prodlužování již existujícího patrona, i když tam prázdnou adresu 02 nechám, tak i když ji smažu a zůstane tam jen 01, tak adresa 02 zase vznikne/doplní se o pole jméno.
![image](https://github.com/LIBCAS/BankID-Registrator/assets/18327175/54ddbb9a-3736-41fd-aa33-8f63520cbb19)

Tzn. pokud jsou všechna pole v kontaktní adrese prázdná i při prodlužování => nevytvořit adresu 02 v Alephu

**Comment by jandera** [comment]
@TOA-Anakin Už se nevytvoří prázdná 02, ale když je kontaktní adresa vyplněná a je vyplněný i e-mail, tak ten e-mail je jen v adrese 01 a nikoli také v 02, měl by být uveden u obou a to samé je i s telefonním číslem.

![image](https://github.com/user-attachments/assets/c4261c25-f543-46d7-9e8f-1414b9358142)

**Comment by jandera** [comment]
@TOA-Anakin Taky by ve formuláři nemělo být editovatelní pole pro jméno v kontaktní adrese, ale mělo by tam být to samé jako v 01
![image](https://github.com/user-attachments/assets/ec2cd5b4-d995-4202-b38c-5a8a929f6a82)

**Comment by TOA-Anakin** [comment]
@jandera Tyto issues ohledně kontakní adresy by už měly být vyřesené

**Comment by jandera** [comment]
@TOA-Anakin Super, zavírám.
