### ISSUE TITLE
Adresy obecně - napojit na mapy.cz

### ISSUE THREAD

**Issue by jandera** [LIBCAS/BankID-Registrator#8]
@TOA-Anakin Bylo by fajn, aby se získaná pole adres nejprve prohnala přes tu fičuru co máme v registračním klientovi, aby pak v Alephu vypadaly stejně/dobře
![image](https://github.com/LIBCAS/BankID-Registrator/assets/18327175/066838ac-ded0-4124-98e0-80de8bb36b0e)

**Comment by TOA-Anakin** [comment]
@jandera Toto by melo byt hotovo uz pred 3 tydny

**Comment by jandera** [comment]
@TOA-Anakin OK, zavírám.
